# Site
repository: lubuss/lubuss.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Luke Busstra
title: Software Engineer
phone: +614 1033 7037
email: luke.busstra@gmail.com
address: Melbourne, Australia
# email_title: Email (Email title override)
# phone_title: Phone (Phone title override)
website: https://lubuss.github.io
website_title: Resume

# Dark Mode (true/false/never)
darkmode: false
darktoggle: true

# Social links
github_username:  lubuss
linkedin_username: lukebusstra

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "G-LTE1YM2FBL"
gtag: "G-LTE1YM2FBL"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  With over 10+ years of software engineering experience and a business management background, I'm a problem solver who excels at tackling complex projects while prioritizing stakeholder values. Collaboration is central to my approach, embracing diverse team input during project planning. I advocate for agile systems engineering principles and firmly believe in overcoming challenges through resourceful solutions. My leadership style adapts to the situation, often leaning towards transformational, delegate, and coaching styles to foster growth. As an ambivert, I seamlessly transition between introverted contemplation and extroverted communication. With prior business management experience, I offer a well-rounded perspective to every project.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Zeller
        sub_title: Software Engineer
        caption: September 2021 - Present
        link: https://www.myzeller.com.au/
        description: | # this will include new lines to allow paragraphs
          ***Backend for Frontend Payment Domains:*** As the owner and technical lead, I architected the Card Not Present Payment Domain, overseeing the successful introduction of new features and payment methods. This reduced regression bugs through a comprehensive testing approach, including unit, system, integration, and end-to-end testing.

          **Attribution Domain:** Led the design and architecture of the System-Wide Attribution Domain and associated services, significantly improving data attribution across the organization.

          **Skills**: <mark>EDA</mark>, <mark>CQRS</mark>, <mark>NodeJs</mark>, <mark>Typescript</mark>, <mark>Payments</mark>, <mark>jest</mark>, <mark>Git</mark>, <mark>AWS</mark>, <mark>Postgres</mark>, <mark>Jira</mark>, <mark>Dynamodb</mark>, <mark>SQS</mark>, <mark>EventBridge</mark>, <mark>EventStore</mark>, <mark>Lambda</mark>
      - layout: left
        title: Quest Payment Systems
        sub_title: Software Engineer
        caption: March 2020 - September 2021
        link: https://www.questpaymentsystems.com/
        description: | # this will include new lines to allow paragraphs
          **Alternative Payments Domain:** Managed various payment methods, including ZipPay and Humm. Architected a new reporting system to replace the legacy system, ensuring accurate and efficient reporting. Diligently monitored, analyzed, diagnosed system logs, and resolved issues promptly.

          **Cross-functional Collaboration:** Collaborated with other engineering teams and projects to align with business objectives and customer requirements.

          **Skills**: <mark>NodeJs</mark>, <mark>Typescript</mark>, <mark>Python</mark>, <mark>Kotlin</mark>, <mark>Android</mark>, <mark>Express</mark>, <mark>Ecommerce</mark>, <mark>POS</mark>, <mark>jest</mark>, <mark>Django</mark>, <mark>Git</mark>, <mark>Jenkins</mark>, <mark>Kubernetes</mark>, <mark>Docker</mark>, <mark>AWS</mark>, <mark>Firebase</mark>, <mark>MSSQL</mark>, <mark>Postgres</mark>, <mark>ElasticSearch</mark>, <mark>Jira</mark>
      - layout: left
        title: Cirrus Logic, Inc.
        sub_title: Software Engineer
        caption: January 2017 - June 2019
        link: https://www.cirrus.com/
        description: | # this will include new lines to allow paragraphs
          **Audio Tuning Tools Domain:** Automated the audio tuning spec definition process to user interface generation. Developed an automated system test framework to verify audio tuning spec definition to user interface generation. Modernized a legacy codebase for multi-OS support.

          **Android Audio SDK Ownership:** Owned and maintained the Android Audio SDK for Cirrus Logic Audio Chips, ensuring compatibility with Android OEMs' devices.     

          **Skills**: <mark>C#</mark>, <mark>C</mark>, <mark>Java</mark>, <mark>react</mark>, <mark>Android</mark>, <mark>NUnit</mark>, <mark>Git</mark>, <mark>SVN</mark>, <mark>Jenkins</mark>, <mark>Docker</mark>, <mark>AWS</mark>, <mark>NodeJs</mark>, <mark>Jira</mark>
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: My Dogs Day
        caption: 2019 - Present
        link: https://demo.mydogsday.com
        link_text:  |
          https://demo.mydogsday.com (Username: demo@mydogsday.com, Password: MyDogsDay123)
        description: | # this will include new lines to allow paragraphs
          Led the end-to-end development of a multi-platform offline support software application, encompassing requirement gathering, design, architectural planning, and successful implementation. This software efficiently oversees the entire business operations of my partner's dog walking company.

          **Skills**: <mark>Flutter</mark>, <mark>Dart</mark>, <mark>Google Cloud</mark>, <mark>Firebase</mark>, <mark>NodeJs</mark>, <mark>React/Reduce</mark>, <mark>AWS</mark>, <mark>Mongo</mark>, <mark>Git</mark>, <mark>GitHub Actions</mark> <mark>Jenkins</mark>
      - layout: left
        title: Cezerin 
        caption: 2019 - 2020
        link: https://github.com/Cezerin2/cezerin2
        link_text: https://github.com/Cezerin2/cezerin2
        additional_links:
          - icon: fab fa-github
            url: https://github.com/Cezerin2/cezerin2
        description: | # this will include new lines to allow paragraphs
          Revitalized the Cezerin populator open-source ecommerce application, introducing new features and automation. Spearheaded the creation, testing, and deployment of web application build pipelines. Pioneered scalable AWS implementation strategies.

          **Skills**: <mark>react/reduce</mark>, <mark>Docker</mark>, <mark>NodeJs</mark>, <mark>git</mark>, <mark>Linux</mark>, <mark>Mongo</mark>, <mark>Express</mark>, <mark>AWS</mark>, <mark>Ecommerce</mark>

  - title: Education
    layout: list
    content:
      - layout: left
        title: Queensland University of Technology
        sub_title: BA Engineering in Computer Software and Systems
        caption: 2013 - 2017
        description: | # this will include new lines to allow paragraphs
          **Achievements:** Graduate with GPA 6 with First Class Honours, Vacation Research Assistant

          **Programming Coursework:** Cloud Computing, Machine Learning, Data Structures and Algorithms, Networks, High Performance and Parallel Computing, Real-Time Systems, Systems Programming 
          
          **EE Coursework:** Microprocessors and Digital Systems, Circuits, Engineering Problem Solving, Engineering Mathematics, Electrical Energy and Measurements
      - layout: left
        title: Leadership, Development and Innovation Program
        sub_title: Queensland University of Technology
        description: | # this will include new lines to allow paragraphs
          **Coursework:** Adaptive Leadership, Communication Styles, Creative & Divergent Thinking, Facilitation Workshop, Group Decision-Making & Consensus Building, Leading High Performance, Learning Teams, Motivating Teams, Small Group/Team Dynamics, Time Management
  # - title: When I am not programming
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
