# Site
repository: lubuss/lubuss.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Lucy (Luke) Busstra
title: Technical Lead & Software Engineer
# phone: +614 1033 7037
email: luke.busstra@gmail.com
address: Melbourne, Australia
# email_title: Email (Email title override)
# phone_title: Phone (Phone title override)
website: https://lubuss.github.io
website_title: Resume

# Dark Mode (true/false/never)
darkmode: false
darktoggle: true

# Social links
github_username:  lubuss
linkedin_username: lukebusstra
print: true

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "G-LTE1YM2FBL"
gtag: "G-LTE1YM2FBL"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_title: Professional Overview
about_content: | # this will include new lines to allow paragraphs
  <b>Technical Lead and Software Engineer</b> with a passion for building modular, 
  scalable, and maintainable systems. I specialize in designing clear, testable 
  architectures that prioritize resilience, readability, and long-term team 
  velocity. With hands-on leadership experience, I drive engineering best 
  practices, enable clean code culture, and guide teams through complex 
  technical decisions from system design to production reliability.

content:
  - title: Areas of Expertise
    layout: list
    content:
      - layout: left-expertise
        sub_title: Professional Skills
        description: |
          Driving Scalable System Design,
          Technical Vision & Decision-Making,
          Performance Optimization & Reliability Engineering,
          Engineering Excellence (Code Quality, Testing Strategies, Maintainability),
          DevOps & Tooling Enablement,
          Agile Delivery & Iterative Development,
          Prioritization, Scope Management & Risk Assessment,
          Cross-Functional Collaboration & Communication,
          Mentorship & Team Enablement,
          Delegation & Empowerment,
          Stakeholder Management,
          Feedback Delivery & Coaching,
          Empathy & Emotional Intelligence,
          Clarity of Communication,
          Accountability & Ownership,
          Growth Mindset & Continuous Improvement,
          Team Building & Leadership
          C4 Modeling for Architecture Visualization
      - layout: left-expertise
        sub_title: Technical Skills
        description: |
          Technical Leadership (System Design, Architecture Ownership, Mentorship),
          Backend Engineering (NodeJs/Typescript, Golang, Language-Agnostic),
          API Design & Management (REST, GraphQL),
          Database Design & Management (Aurora/Postgres, DynamoDB, Firebase),
          Infrastructure & DevOps (AWS CloudFormation, Terraform, Serverless, GitHub Actions),
          Observability & Monitoring (Datadog, Sentry, CloudWatch),
          Microservices & Event-driven Architecture (AWS SQS, AWS EventBridge, CQRS),
          Scalability & Performance Optimization,
          Testing & Quality Assurance (Unit, System, Integration, E2E),
          Code Review Mastery,
          RFCs & Proposal Writing,
          Technical Writing
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Zeller
        sub_title: Tech Lead & Senior Software Engineer
        caption: Sept 2021 - Present
        link: myzeller.com
        description: | # this will include new lines to allow paragraphs
          Led a 10-engineer team within Zeller’s BFF Payments group, driving the design and delivery 
          of event-driven backend systems that power customer transactions, enhance CRM integrations, 
          and ensure platform scalability and reliability. Championed engineering best practices, 
          fostered team growth, and aligned technical solutions with business objectives.
        highlights:
          - <b>Architected and owned 6 core components</b> in Go and TypeScript, leading the design 
            of 4 systems to enable event-driven workflows and seamless frontend integration.
          - <b>Managed and optimized 15+ microservices</b> across Zeller’s BFF platform, establishing 
            patterns for scalability, resilience, and deployment consistency.
          - <b>Designed and launched 4 new payment channels</b>, delivering authentication, event 
            processing, and reporting flows that increased transaction volume.
          - <b>Led the design of a greenfield on-premises payments integration platform</b>,
            enabling first of its kind on-premises pay at table integration.
          - <b>Implemented a comprehensive BFF test pyramid</b>, improving test coverage across unit, 
            system, integration, and contract levels, reducing production bugs.
          - <b>Standardized observability practices</b>, reducing noise and improving traceability, 
            which enhanced on-call debugging efficiency.
          - <b>Mentored and developed engineering talent</b>, guiding a senior engineer into a team 
            lead role and fostering expertise in event-driven architecture and system design.
          - <b>Integrated AI-driven solutions</b> to enhance team productivity, streamline workflows, 
            and improve decision-making in system design
        skills:
          - Backend Engineering [NodeJs (Typescript), Golang]
          - Event-Driven Architecture [CQRS, AWS SQS, AWS EventBridge]
          - Cloud Infrastructure [AWS (Lambdas, RDS, DynamoDB, ApiGateway, CloudFormation, CodePipeline)]
          - CI/CD [GitHub Actions, CI/CD Pipelines, AWS CodeBuild]
          - Observability [Datadog, Monitoring, Debugging]
          - Tools [Git, Jira, Confluence]
      - layout: left
        title: Quest Payment Systems
        sub_title: Senior Software Engineer
        caption: March 2020 - Sept 2021
        link: questpaymentsystems.com
        description: | # this will include new lines to allow paragraphs
          Senior Software Engineer for the Innovation team, responsible for the development of new products and features for Quest Payment Systems. Played a
          critical role in enhancing the company’s payment solutions, ensuring high availability, and providing quick resolution of issues.
        highlights:
          - <b>ZipPay Integration:</b> Directed the successful implementation of the <a href="https://www.questpaymentsystems.com/zippay.html" class="link" 
            target="_blank">ZipPay integration</a>, enhancing the company's payment solutions and improving customer satisfaction.
          - <b>Real-Time Transaction Reporting System:</b> Developed a next-generation real-time transaction reporting system, supporting alternative payment
            methods and improving transaction visibility for merchants and support teams.
          - <b>Support for Alternative Payment Systems:</b> Provided critical support for alternative payment systems, ensuring high availability and quick 
            resolution of issues.
          - <b>Next-Gen Payment Systems Development:</b> Contributed to the development of next-gen payment systems like <a href="https://airpaypos.com/" 
            class="link" target="_blank">Air Pay</a>, <a href="https://www.questpaymentsystems.com/tap-on-phone.html" class="link" target="_blank">Tap on 
            Phone</a>, and <a href="https://www.donationpointgo.com/" class="link" target="_blank">Donation Point Go</a>. Supported their successful launch
            and operation.
        skills:
          - NodeJs [Javascript, Express]
          - Python [Django]
          - Android [Kotlin]
          - Jenkins
          - Docker
          - Firebase
          - MSSQL
          - AWS
          - ElasticSearch
      - layout: left
        title: Cirrus Logic, Inc.
        sub_title: Software Engineer
        caption: Jan 2017 - June 2019
        link: cirrus.com
        description: | # this will include new lines to allow paragraphs
          Software Engineer in the Audio Tuning Tools team, part of the Australian Innovation department. Responsible for developing and maintaining the tools
          used by Audio Engineers to tune Cirrus Logic Audio Chips.
        highlights:
          - <b>Tuning Specification UI Automation:</b> Automated the process of turning Audio Engineers' specification documents into a tooling UI, automating 
            80% of the configuration process, and reducing the time to generate a UI from 1 day to an hour.
          - <b>Tuning Specification Automation Testing:</b> Developed a UI automation framework for the audio tuning tools domain, reducing manual 
            testing time by 60%, detecting specification errors in 40% of UIs.
          - <b>Android Audio SDK Ownership:</b> Owned and maintained the Android Audio SDK for Cirrus Logic Audio Chips, ensuring compatibility with Android 
            OEMs' devices.
        skills:
          - C#
          - C
          - Android [Java]
          - NodeJs [React]
          - SonarCloud
          - Gerrit
          - SVN
          - Jenkins
          - Docker
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: My Dogs Day
        caption: 2019 - Present
        link: demo.mydogsday.com
        description: | # this will include new lines to allow paragraphs
          A SaaS platform designed to manage dog walking businesses, featuring offline 
          support, multi-user functionality, and real-time data synchronization. Initially
          developed as a React single-page application hosted on AWS, it evolved into a
          Flutter-based mobile application with a Firebase backend. The platform handles
          customer management, appointment scheduling, invoicing, and regional operations.
          This project serves as a playground for experimenting with new technologies and
          implementing best practices in software development.
        skills:
          - Flutter
          - Dart
          - Google Cloud
          - Firebase
          - NodeJs
          - Git
          - GitHub Actions
      - layout: left
        title: Cezerin 
        caption: 2019 - 2020
        link: github.com/Cezerin2/cezerin2
        link_text: github.com/Cezerin2/cezerin2
        additional_links:
          - icon: fab fa-github
            url: github.com/Cezerin2/cezerin2
        description: | # this will include new lines to allow paragraphs
          Contributed to revitalizing the Cezerin open-source e-commerce application,
          introducing new features and automation. Spearheaded the creation, testing,
          and deployment of web application build pipelines. Pioneered scalable AWS
          implementation strategies, which influenced my approach to modern cloud-native
          architectures.

        skills:
          - React/Redux
          - Docker
          - NodeJs [Express, React/Redux]
          - git
          - MongoDb

  - title: Professional Development
    layout: list
    content:
      - layout: left
        title: YOW! Conferences
        caption: 2012 - Present
        description: |
          Regular attendee of YOW! Conferences, engaging with industry leaders 
          and staying updated on cutting-edge trends in software engineering, 
          architecture, and backend technologies.

  - title: Education
    layout: list
    content:
      - layout: top
        title: Queensland University of Technology
        sub_title: BA Engineering in Computer Software and Systems
        caption: 2013 - 2017
        quote: Graduate with <b>GPA 6</b> with <b>First Class Honours</b>
        description: | # this will include new lines to allow paragraphs
          **Programming Coursework:** Cloud Computing, Machine Learning, Data Structures and Algorithms, Networks, High 
          Performance and Parallel Computing, Real-Time Systems, Systems Programming 
          
          **Electrical Engineering Coursework:** Microprocessors and Digital Systems, Circuits, Engineering Problem Solving,
          Engineering Mathematics, Electrical Energy and Measurements

          <h4>Achievements</h4>
        highlights:
          - <b>Vacation Research Assistant:</b> Conducted research into Application Search, developed a test bed for the research, 
            and implemented a prototype for the research.
          - <b>Leadership, Development and Innovation Program:</b>  Participated in a program that focused on developing leadership
            skills, fostering innovation, and enhancing personal development.
          - <b>Final Year Capstone:</b> GPS-OLRSd, Multi-UAV Flying Ad-Hoc Network (FANETs) for real-time communication in Disaster
            Recovery / rural areas.
 
  # - title: When I am not programming
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
